#!/usr/bin/env python
"""Nitime release build script.
"""
from toollib import *

# Find our directory and go one above, regardless of where we were called from
my_dir = os.path.split(os.path.abspath(__file__))[0]
cd(pjoin(my_dir, '..'))

# Load release info
execfile(pjoin('nitime','version.py'))

# Check that everything compiles
compile_tree()

# Cleanup
for d in ['build','dist', pjoin('doc','_build'), pjoin('docs','dist')]:
    if os.path.isdir(d):
        remove_tree(d)

# Build source and binary distros
sh('./setup.py sdist --formats=gztar,zip')

# Build eggs
sh('python ./setup_egg.py bdist_egg')

# Create a windows distribution
# sh("python setup.py bdist_wininst")

# Change name so retarded Vista runs the installer correctly
# sh("rename 's/linux-i686/win32-setup/' dist/*.exe")
